### ISSUE TITLE
Margo errror

### ISSUE THREAD

**Issue by ekarlso** [DisposaBoy/GoSublime-next#5]
| GoSublime error: MarGo build failed
|                > This is possibly a bug or miss-configuration of your environment.
|                > For more help, please file an issue with the following build output
|                > at: https://github.com/DisposaBoy/GoSublime/issues/new
|                > or alternatively, you may send an email to: gosublime@dby.me
|                > 
|                > 
|                > cmd: `['/usr/bin/go', 'build', '-tags', 'gosublime', '-v', '-x', '-o', '~/.config/sublime-text-3/Packages/User/GoSublime/linux-x64/2014.09.22-020125_go1.2.1/bin/margo', 'gosubli.me/margo']`
|                > stdout: ``
|                > stderr:`WORK=/tmp/go-build476131580
|                > can't load package: package gosubli.me/margo: cannot find package "gosubli.me/margo" in any of:
|                >  /usr/lib/go/src/pkg/gosubli.me/margo (from $GOROOT)
|                >  ~/.config/sublime-text-3/Packages/GoSublime/src/gosubli.me/margo (from $GOPATH)`
|                > exception:`None`
|   install state: busy
| sublime.version: 3065
| sublime.channel: stable
|       about.ann: a14.03.28-1
|   about.version: r13.12.26-3
|         version: 2014.09.22-020125
|        platform: linux-x64
|            ~bin: ~/.config/sublime-text-3/Packages/User/GoSublime/linux-x64/2014.09.22-020125_go1.2.1/bin
|          go.exe: /usr/bin/go (ok)
|       margo.exe: margo (missing)
|      go.version: go1.2.1
|          GOROOT: /usr/lib/go
|          GOPATH: ~/projects/golang
|       MARGOPATH: ~/.config/sublime-text-3/Packages/GoSublime
|           GOBIN: (not set)
|       cfg.shell: []
|       env.shell: /bin/bash
|       shell.cmd: ['/bin/bash', '-l', '-c', '${CMD}']

**Comment by narma** [comment]
@ekarlso Got same error and then found a solution, you should rename directory from `GoSublime-next` to `GoSublime` to avoid this error.
